# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67117fa0b318fb6913b7acfe1f91f3b6f2280e2bbec1ac5f8652df95edbd94d6b051bcbb3dac37d55b92ce99d3700dc244e7efa0fb2859d74c61dc37228e7672

test:
  secret_key_base: 3cf1e1ba4d00af3c9ceeaeb34a432117be08a51211d8b9cfad5f0172c7e4a8558d1ed14ad2e71299bcb9b7dbb49f72f1c0c12f2de31e10686396c7a15a4c24c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
